version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: Builder_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      BUILDER_DB_HOST: db
      BUILDER_DB_PORT: 5432
      BUILDER_DB_NAME: Builder_DB
      BUILDER_DB_USER: postgres
      BUILDER_DB_PASSWORD: admin

      HISTORIAN_DB_HOST: db
      HISTORIAN_DB_PORT: 5432
      HISTORIAN_DB_NAME: Historian_DB
      HISTORIAN_DB_USER: postgres
      HISTORIAN_DB_PASSWORD: admin