version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # LLM
      MODEL_NAME: mistral
      OLLAMA_URL: http://host.docker.internal:11434/api/generate

      # Builder DB
      BUILDER_DB_HOST: host.docker.internal
      BUILDER_DB_PORT: 5432
      BUILDER_DB_NAME: Builder_DB
      BUILDER_DB_USER: postgres
      BUILDER_DB_PASSWORD: admin

      # Historian DB
      HISTORIAN_DB_HOST: host.docker.internal
      HISTORIAN_DB_PORT: 5432
      HISTORIAN_DB_NAME: Historian_DB
      HISTORIAN_DB_USER: postgres
      HISTORIAN_DB_PASSWORD: admin

    extra_hosts:
      - "host.docker.internal:host-gateway"  # needed for Linux
    restart: always